### ISSUE TITLE
The enhanced human detection Yolov8 models 

### ISSUE THREAD

**Issue by scottcali** [tusharsachan15/enhanced_human_detection_model_using_Yolov8#1]
Hello,

   Great job!

    Could you please share the enhanced human detection Yolov8 models?

   Thanks!

-Scott

**Comment by tusharsachan15** [comment]
The weights of each of the file were very large; hence, I could not upload it to github, this is my mail id please contact me for the weights there.

tusharsachan2002@gmail.com
